#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          Battleship server
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initscript for battleship server
### END INIT INFO

# Author: Viacheslav V. Kovalev <kovyl2404@gmail.com>

DESC="Battleship network gaming server"
DAEMON=/opt/battleship-server/bin/battleship-server

[ -f /etc/default/battleship-server ] && . /etc/default/battleship-server


case "$1" in
	start)
		echo "Starting battleship server"
		su $RUNNER_USER -c "$DAEMON start"
		exit $?
	;;
	stop)
		echo "Stopping battleship server"
		su $RUNNER_USER -c "$DAEMON stop"
		exit $?
	;;
	status)
		su $RUNNER_USER -c "$DAEMON ping"
		exit $?
	;;
	attach)
		su $RUNNER_USER -c "$DAEMON attach"
		exit $?
	;;
	*)
		echo "Unexpected action $1"
		exit 1
esac

